[
  {
    courseCode: "EEX3467",
    courseName: "Software Engineering Concepts",
    prerequisites: [],
    semesters: [1],
    courseCoordinator: "Dr. H.M.M. Caldera",
    credits: 3,
    subjectLevel: 3,
    compulsory: true,
    passedCreditsRequired: 0,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: "average",
    },
    recommendedNextSubjects: ["EEI4267", "EEI4362", "EEX4465"],
  },
  {
    courseCode: "EEI3346",
    courseName: "Web Application Development",
    prerequisites: [],
    semesters: [1],
    courseCoordinator: "Prof. H. Sriyananda",
    credits: 3,
    subjectLevel: 3,
    compulsory: true,
    passedCreditsRequired: 0,
    eligibilityCriteria: {
      type: "best_cat_avg_tma",
      cat: "average",
      tma: "best",
      lab: "average",
    },
    recommendedNextSubjects: ["EEI4366", "EEY4189"],
  },
  {
    courseCode: "EEI3262",
    courseName: "Introduction to Object Oriented Programming",
    prerequisites: [],
    semesters: [2],
    courseCoordinator: "Dr. K.A.C. Udayakumar",
    credits: 3,
    subjectLevel: 3,
    compulsory: true,
    passedCreditsRequired: 0,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: ["EEI4362"],
  },
  {
    courseCode: "EEI3266",
    courseName: "Information Systems and Data Management",
    prerequisites: [],
    semesters: [1],
    courseCoordinator: "Eng. C. J. Basnayakege",
    credits: 3,
    subjectLevel: 3,
    compulsory: true,
    passedCreditsRequired: 0,
    eligibilityCriteria: {
      type: "best_cat_avg_tma",
      cat: "best",
      tma: "average",
      lab: "average",
    },
    recommendedNextSubjects: ["EEI4366"],
  },
  {
    courseCode: "EEX3373",
    courseName: "Communication and Computer Technology",
    prerequisites: ["AGM3263 (CR)", "EEX3467 (CR)"],
    semesters: [1, 2],
    courseCoordinator: "Eng. Dr. G. Anthonys",
    credits: 3,
    subjectLevel: 3,
    compulsory: true,
    passedCreditsRequired: 0,
    eligibilityCriteria: {
      type: "miniProject60_rest40",
      cat: "best",
      tma: "best",
      lab: "average",
    },
    recommendedNextSubjects: ["EEI4267", "EEI4362"],
  },
  {
    courseCode: "AGM3263",
    courseName: "Communication Skills",
    prerequisites: [],
    semesters: [1, 2],
    courseCoordinator: "Dr. L.S.K. Udugama",
    credits: 3,
    subjectLevel: 3,
    compulsory: true,
    passedCreditsRequired: 0,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: [],
  },
  {
    courseCode: "MHZ3459",
    courseName: "Basic Mathematics for Computing",
    prerequisites: [],
    semesters: [1, 2],
    courseCoordinator: "Prof. Sunil Thrikawala",
    credits: 3,
    subjectLevel: 3,
    compulsory: true,
    passedCreditsRequired: 0,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      " tma": "average",
      lab: null,
    },
    recommendedNextSubjects: [],
  },
  {
    courseCode: "EEI3269",
    courseName: "Introduction to Mobile Application Development",
    prerequisites: [],
    semesters: [2],
    courseCoordinator: "Dr. K.D.N. Kumari",
    credits: 2,
    subjectLevel: 3,
    compulsory: false,
    passedCreditsRequired: 0,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: [],
  },
  {
    courseCode: "EEI3372",
    courseName: "Programming in Python",
    prerequisites: [],
    semesters: [1],
    courseCoordinator: "Mr. M.S.S. Perera",
    credits: 3,
    subjectLevel: 3,
    compulsory: false,
    passedCreditsRequired: 0,
    eligibilityCriteria: {
      type: "best_cat_avg_tma",
      cat: "average",
      tma: "best",
      lab: null,
    },
    recommendedNextSubjects: [],
  },
  {
    courseCode: "EEM3366",
    courseName: "Introduction to Business Studies",
    prerequisites: [],
    semesters: [2],
    courseCoordinator: "Eng. W.D.S.S. Bandara",
    credits: 3,
    subjectLevel: 3,
    compulsory: false,
    passedCreditsRequired: 0,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: [],
  },
  {
    courseCode: "EEI4267",
    courseName: "Requirement Engineering",
    prerequisites: ["EEX3467 (P)"],
    semesters: [3],
    courseCoordinator: "Eng. Dr. G. Anthonys",
    credits: 3,
    subjectLevel: 4,
    compulsory: true,
    passedCreditsRequired: 15,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: ["EEI6567", "EEY6689"],
  },
  {
    courseCode: "EEI4362",
    courseName: "Object Oriented Design",
    prerequisites: ["EEI3262 (CA)", "EEX3467 (CA)", "Pass in 15 credits"],
    semesters: [3],
    courseCoordinator: "Dr. A.P. Madurapperuma",
    credits: 3,
    subjectLevel: 4,
    compulsory: true,
    passedCreditsRequired: 15,
    eligibilityCriteria: {
      type: "best_cat_avg_tma",
      cat: "average",
      tma: "best",
      lab: "average",
    },
    recommendedNextSubjects: ["EEI6567", "EEY6689"],
  },
  {
    courseCode: "EEX4465",
    courseName: "Data Structures and Algorithms",
    prerequisites: ["EEX3373 (CA)", "MHZ4256 (CR)", "Pass in 15 credits"],
    semesters: [3],
    courseCoordinator: "Prof. H. Sriyananda",
    credits: 3,
    subjectLevel: 4,
    compulsory: true,
    passedCreditsRequired: 15,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: ["EEI5270", "EEY6689"],
  },
  {
    courseCode: "MHZ4256",
    courseName: "Mathematics for Computing",
    prerequisites: [],
    semesters: [3],
    courseCoordinator: "Prof. Sunil Thrikawala",
    credits: 3,
    subjectLevel: 4,
    compulsory: true,
    passedCreditsRequired: 15,
    eligibilityCriteria: {
      type: "cat60_tma40",
      " cat": "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: ["MHZ5375"],
  },
  {
    courseCode: "EEI4361",
    courseName: "User Experience Engineering",
    prerequisites: ["EEX3467 (CA)", "Pass in 15 credits"],
    semesters: [4],
    courseCoordinator: "Dr. (Ms.) D.D.M. Ranasinghe",
    credits: 3,
    subjectLevel: 4,
    compulsory: true,
    passedCreditsRequired: 15,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: ["EEI6567"],
  },
  {
    courseCode: "EEI4366",
    courseName: "Data Modelling and Database Systems",
    prerequisites: ["EEI3266 (CA)", "Pass in 15 credits"],
    semesters: [4],
    courseCoordinator: "Eng (Mrs) K.M.G.Y. Sewwandi",
    credits: 3,
    subjectLevel: 4,
    compulsory: true,
    passedCreditsRequired: 15,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: "average",
    },
    recommendedNextSubjects: ["EEI5270"],
  },
  {
    courseCode: "EEX4464",
    courseName: "Operating Systems and System Programming",
    prerequisites: ["EEX3373 (CA)", "MHZ4256 (CA)", "Pass in 15 credits"],
    semesters: [4],
    courseCoordinator: "Eng. Dr. W.D.S.S. Bandara",
    credits: 3,
    subjectLevel: 4,
    compulsory: true,
    passedCreditsRequired: 15,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: ["EEY6689"],
  },
  {
    courseCode: "EEI4374",
    courseName: "Computer Networks and Security",
    prerequisites: ["EEX3373 (CA)", "EEX4465 (CA)", "Pass in 15 credits"],
    semesters: [4],
    courseCoordinator: "Dr. K.A.C. Udayakumar",
    credits: 3,
    subjectLevel: 4,
    compulsory: true,
    passedCreditsRequired: 15,
    eligibilityCriteria: {
      type: "best_cat_avg_tma",
      cat: "average",
      tma: "best",
      lab: "average",
    },
    recommendedNextSubjects: ["EEY6689"],
  },
  {
    courseCode: "EEI4385",
    courseName: "Emerging Technologies",
    prerequisites: ["Pass in 15 credits"],
    semesters: [4],
    courseCoordinator: "Mr. M.S.S. Perera",
    credits: 3,
    subjectLevel: 4,
    compulsory: false,
    passedCreditsRequired: 15,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: [],
  },
  {
    courseCode: "EEI4271",
    courseName: "Cloud Computing",
    prerequisites: ["Pass in 15 credits"],
    semesters: [4],
    courseCoordinator: "Dr. H.M.M. Caldera",
    credits: 3,
    subjectLevel: 4,
    compulsory: false,
    passedCreditsRequired: 15,
    eligibilityCriteria: {
      type: "best_cat_avg_tma",
      cat: "average",
      tma: "best",
      lab: null,
    },
    recommendedNextSubjects: [],
  },
  {
    courseCode: "EEI5270",
    courseName: "Advanced Database Systems",
    prerequisites: ["EEI4366 (CA)", "Pass in 30 credits"],
    semesters: [5],
    courseCoordinator: "Dr. L.S .K. Udugama",
    credits: 3,
    subjectLevel: 5,
    compulsory: true,
    passedCreditsRequired: 30,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: "average",
    },
    recommendedNextSubjects: ["EEI6261", "EEY6689"],
  },
  {
    courseCode: "EEI5375",
    courseName: "Advanced Data Structures",
    prerequisites: ["EEX4465 (CA)", "MHZ4256 (CA)", "Pass in 30 credits"],
    semesters: [5],
    courseCoordinator: "Prof. H. Sriyananda",
    credits: 3,
    subjectLevel: 5,
    compulsory: true,
    passedCreditsRequired: 30,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: ["EEI6263"],
  },
  {
    courseCode: "EEY5189",
    courseName: "Machine Learning Fundamentals",
    prerequisites: ["EEX3373 (CA)", "Pass in 30 credits"],
    semesters: [5],
    courseCoordinator: "Eng. Dr. G. Anthonys",
    credits: 3,
    subjectLevel: 5,
    compulsory: true,
    passedCreditsRequired: 30,
    eligibilityCriteria: {
      type: "best_cat_avg_tma",
      cat: "average",
      tma: "best",
      lab: "average",
    },
    recommendedNextSubjects: ["EEY6280"],
  },
  {
    courseCode: "EEY5267",
    courseName: "Software Project Management",
    prerequisites: ["EEX3467 (CA)", "Pass in 30 credits"],
    semesters: [5],
    courseCoordinator: "Eng. C. J. Basnayakege",
    credits: 3,
    subjectLevel: 5,
    compulsory: true,
    passedCreditsRequired: 30,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: ["EEY6364"],
  },
  {
    courseCode: "EEI5368",
    courseName: "Big Data and Analytics",
    prerequisites: ["EEI4366 (CA)", "Pass in 30 credits"],
    semesters: [6],
    courseCoordinator: "Dr. K.D.N. Kumari",
    credits: 3,
    subjectLevel: 5,
    compulsory: false,
    passedCreditsRequired: 30,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: "average",
    },
    recommendedNextSubjects: ["EEY6280"],
  },
  {
    courseCode: "EEY6280",
    courseName: "Deep Learning Techniques",
    prerequisites: ["EEY5189 (CA)", "Pass in 45 credits"],
    semesters: [6],
    courseCoordinator: "Dr. K.A.C. Udayakumar",
    credits: 3,
    subjectLevel: 6,
    compulsory: true,
    passedCreditsRequired: 45,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: "average",
    },
    recommendedNextSubjects: [],
  },
  {
    courseCode: "EEY6261",
    courseName: "Advanced Cloud Computing",
    prerequisites: ["EEI4271 (CA)", "Pass in 45 credits"],
    semesters: [6],
    courseCoordinator: "Eng. W.D.S.S. Bandara",
    credits: 3,
    subjectLevel: 6,
    compulsory: true,
    passedCreditsRequired: 45,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      "lab ": "average",
    },
    recommendedNextSubjects: [],
  },
  {
    courseCode: "EEY6364",
    courseName: "Agile Software Development",
    prerequisites: ["EEY5267 (CA)", "Pass in 45 credits"],
    semesters: [6],
    courseCoordinator: "Dr. (Ms.) D.D.M. Ranasinghe",
    credits: 3,
    subjectLevel: 6,
    compulsory: true,
    passedCreditsRequired: 45,
    eligibilityCriteria: {
      type: "best_cat_avg_tma",
      cat: "average",
      tma: "best",
      lab: null,
    },
    recommendedNextSubjects: [],
  },
  {
    courseCode: "EEY6389",
    courseName: "Cyber Security Essentials",
    prerequisites: ["EEI4374 (CA)", "Pass in 45 credits"],
    semesters: [6],
    courseCoordinator: "Mr. M.S.S. Perera",
    credits: 3,
    subjectLevel: 6,
    compulsory: true,
    passedCreditsRequired: 45,
    eligibilityCriteria: {
      type: "cat60_tma40",
      cat: "best",
      tma: "average",
      lab: "average",
    },
    recommendedNextSubjects: [],
  },
  {
    courseCode: "EEI6293",
    courseName: "Blockchain and Distributed Ledger Technology",
    prerequisites: ["EEI4267 (CA)", "Pass in 45 credits"],
    semesters: [6],
    courseCoordinator: "Prof. Sunil Thrikawala",
    credits: 3,
    subjectLevel: 6,
    compulsory: false,
    passedCreditsRequired: 45,
    eligibilityCriteria: {
      type: "best_cat_avg_tma",
      cat: "best",
      tma: "average",
      lab: null,
    },
    recommendedNextSubjects: [],
  },
];
