export const responseData = {
  success: {
    user: {
      name: "Pasindu",
      email: "pasindu@gmail.com",
      role: "STUDENT",
    },
    message: "No courses enrolled yet. Here are some recommended courses.",
    recommendedSubjects: [
      {
        _id: "672075bb10269fd9059f00c7",
        courseCode: "AGM3263",
        courseName: "Communication Skills",
        courseCoordinator: "Dr. L.S.K. Udugama",
        credits: 3,
        compulsory: true,
      },
      {
        _id: "672075bb10269fd9059f00bd",
        courseCode: "EEX3467",
        courseName: "Software Engineering Concepts",
        courseCoordinator: "Dr. H.M.M. Caldera",
        credits: 3,
        compulsory: true,
      },
      {
        _id: "672075bb10269fd9059f00a1",
        courseCode: "CSC2412",
        courseName: "Data Structures and Algorithms",
        courseCoordinator: "Prof. J.P. Perera",
        credits: 3,
        compulsory: true,
      },
      {
        _id: "672075bb10269fd9059f00b3",
        courseCode: "MTH1101",
        courseName: "Calculus for Computing",
        courseCoordinator: "Dr. K.W. Wickramasinghe",
        credits: 4,
        compulsory: true,
      },
      {
        _id: "672075bb10269fd9059f00d2",
        courseCode: "PHY1208",
        courseName: "Physics for Computer Science",
        courseCoordinator: "Dr. N.D. Silva",
        credits: 3,
        compulsory: false,
      },
      {
        _id: "672075bb10269fd9059f00e3",
        courseCode: "CSC3434",
        courseName: "Web Application Development",
        courseCoordinator: "Dr. M.T. Fernando",
        credits: 3,
        compulsory: false,
      },
      {
        _id: "672075bb10269fd9059f00f4",
        courseCode: "INF2205",
        courseName: "Database Management Systems",
        courseCoordinator: "Prof. R.M. Jayawardena",
        credits: 3,
        compulsory: true,
      },
      {
        _id: "672075bb10269fd9059f00g1",
        courseCode: "CMP3321",
        courseName: "Artificial Intelligence Basics",
        courseCoordinator: "Dr. V.S. Samarasinghe",
        credits: 3,
        compulsory: false,
      },
      {
        _id: "672075bb10269fd9059f00h2",
        courseCode: "BIO2403",
        courseName: "Bioinformatics",
        courseCoordinator: "Prof. S.P. Gunawardena",
        credits: 3,
        compulsory: false,
      },
      {
        _id: "672075bb10269fd9059f00i3",
        courseCode: "MAT2511",
        courseName: "Discrete Mathematics",
        courseCoordinator: "Dr. K.G. Rathnayake",
        credits: 3,
        compulsory: true,
      },
      {
        _id: "672075bb10269fd9059f00j4",
        courseCode: "ITN3345",
        courseName: "Network Security",
        courseCoordinator: "Dr. S.H. Perera",
        credits: 3,
        compulsory: false,
      },
      {
        _id: "672075bb10269fd9059f00k5",
        courseCode: "CMP3450",
        courseName: "Machine Learning Fundamentals",
        courseCoordinator: "Dr. T.D. Karunaratne",
        credits: 3,
        compulsory: false,
      },
      {
        _id: "672075bb10269fd9059f00l6",
        courseCode: "CSC1101",
        courseName: "Introduction to Computer Science",
        courseCoordinator: "Dr. A.G. Weerakoon",
        credits: 3,
        compulsory: true,
      },
      {
        _id: "672075bb10269fd9059f00m7",
        courseCode: "ITP2200",
        courseName: "Programming in Python",
        courseCoordinator: "Dr. M.R. Dias",
        credits: 3,
        compulsory: false,
      },
      {
        _id: "672075bb10269fd9059f00n8",
        courseCode: "HUM1104",
        courseName: "Ethics in Technology",
        courseCoordinator: "Dr. P.W. Jayasuriya",
        credits: 2,
        compulsory: false,
      },
    ],
  },
};
